-- Migration: Add models table and model_id to posts
-- Models are like users - each model has a profile with all posts generated by it

-- 1. Create models table
CREATE TABLE IF NOT EXISTS public.models (
  id text PRIMARY KEY, -- e.g. 'anthropic/claude-opus-4.5'
  name text NOT NULL, -- e.g. 'Claude Opus 4.5'
  provider text NOT NULL, -- e.g. 'Anthropic'
  description text,
  avatar_url text, -- URL to model's avatar/logo
  is_free boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Trigger for models updated_at
DROP TRIGGER IF EXISTS set_updated_at_models ON public.models;
CREATE TRIGGER set_updated_at_models
BEFORE UPDATE ON public.models
FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- RLS for models (public read)
ALTER TABLE public.models ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Models are viewable by everyone" ON public.models;
CREATE POLICY "Models are viewable by everyone"
  ON public.models FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Models can be inserted" ON public.models;
CREATE POLICY "Models can be inserted"
  ON public.models FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Models can be updated" ON public.models;
CREATE POLICY "Models can be updated"
  ON public.models FOR UPDATE
  USING (true);

-- 2. Add model_id to posts table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'posts' AND column_name = 'model_id'
  ) THEN
    ALTER TABLE public.posts ADD COLUMN model_id text REFERENCES public.models(id) ON DELETE SET NULL;
    CREATE INDEX IF NOT EXISTS idx_posts_model_id ON public.posts (model_id);
  END IF;
END $$;

-- 3. Insert default models
INSERT INTO public.models (id, name, provider, description, is_free) VALUES
  ('x-ai/grok-4.1-fast:free', 'Grok 4.1 Fast', 'xAI', 'Free model, fast but less capable', true),
  ('anthropic/claude-opus-4.5', 'Claude Opus 4.5', 'Anthropic', 'Best for complex code generation', false),
  ('openai/gpt-5.1-codex', 'GPT-5.1-Codex', 'OpenAI', 'Specialized for code generation', false)
ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE public.models IS 'AI models available for generation, each with its own profile';
COMMENT ON COLUMN public.posts.model_id IS 'Reference to the AI model used for generation';
